services:
  web:
    image: img-dj:1.0.0
    container_name: cont-dj
    restart: always
    command: ["sh", "-c", "uv run manage.py migrate --fake-initial && uv run manage.py collectstatic --noinput && uv run manage.py runserver 0.0.0.0:8088"]
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8088:8088"
